name: light_bulb
description: A Flutter app for the upcoming TechTalk about BLoC.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  # DI
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.10.0

  # More linting!
  dart_code_metrics: ^4.21.0

flutter:
  uses-material-design: true
